`timescale 1ns / 1ps

module init_ctrl #(
  parameter integer ADDR_W         = 17,        // PRAM address width
  parameter [ADDR_W-1:0] BASE_ADDR = 17'h00000,  // init start address
  parameter [ADDR_W-1:0] MEM_LIMIT = 17'h01FFF,   // MEM_LIMIT is an exclusive upper bound (init runs while addr < MEM_LIMIT)
  parameter [ADDR_W-1:0] INCR      = 17'd8
)(
  input  wire                 clk,
  input  wire                 rst,

  // -------------------------------------------------------------------------
  // Global control inputs
  // -------------------------------------------------------------------------
  input  wire                 interrupt,       // pause/abort during init
  input  wire                 enable,          // step address (one word)

  // -------------------------------------------------------------------------
  // Encoded FSM state (visible to MemCtrl / top-level)
  // -------------------------------------------------------------------------
  output reg  [2:0]           state,           // 6-state encoding

  // -------------------------------------------------------------------------
  // Datapath control signals (match your control table)
  // -------------------------------------------------------------------------
  output reg                  SPI_rdata_type,  // 0 = INITIALIZATION, 1 = EMBD_READ(load)
  output reg                  PRAM_addr_type,  // 0 = INITIALIZATION, 1 = LOAD/STORE ADDRESS
  output reg                  PRAM_in,         // 0 = INITIALIZATION, 1 = STORE DATA
  output reg                  burst_dim,       // 0 = INITIALIZATION, 1 = LOAD/STORE ADDRESS
  output reg                  ROM_addr_type,   // 0 = init read addr, 1 = EMAB(load/store)
  output reg                  mem_init,        // 1 = init phase (S_START/S_WAIT/S_PAUSE)
  output reg                  first_fetch,
  // -------------------------------------------------------------------------
  // Address generated by internal counter
  // -------------------------------------------------------------------------
  output wire [ADDR_W-1:0]    INITIALIZATION_addr
);

  // -------------------------------------------------------------------------
  // Address counter instance
  // -------------------------------------------------------------------------
  wire [ADDR_W-1:0] count;
  wire last_initialisation;
  reg mem_init_done;

  up_counter #(
    .INCR      (INCR),        // 8 bytes per word
    .LOAD_DIM  (ADDR_W),
    .COUNT_DIM (ADDR_W)
  ) u_addr_cnt (
    .clk        (clk),
    .enable     (enable),
    .reset      (rst),
    .load_value (BASE_ADDR),
    .max_value  (MEM_LIMIT),
    .count      (count)
  );
  assign INITIALIZATION_addr = count;
  assign last_initialisation = (INITIALIZATION_addr >= (MEM_LIMIT - INCR)) ? 1'b1 : 1'b0;

  always @(*) begin
  if (rst)
    mem_init_done <= 1'b0;
  else if (mem_init && enable && (INITIALIZATION_addr >= (MEM_LIMIT - INCR)))
    mem_init_done <= 1'b1;
  end



  // -------------------------------------------------------------------------
  // FSM state encoding (4 states)
  // -------------------------------------------------------------------------
  localparam [2:0]
    S_IDLE    = 3'd0,  // after reset: go to S_START
    S_START   = 3'd1,  // first cycle of init
    S_WAIT    = 3'd2,  // wait for MemCtrl to finish
    S_FIRST_FETCH = 3'd3,//to implement first fetch
    S_SUCCESS = 3'd4;  // init success (terminal) and normal operation

  reg [2:0] state_next;

  // ==========================================================================
  // State register
  // ==========================================================================
  always @(posedge clk or posedge rst) begin
    if (rst)
      state <= S_IDLE;
    else
      state <= state_next;
  end

  // ==========================================================================
  // Next-state logic
  // ==========================================================================
  always @* begin
    state_next = state;

    case (state)
      // After reset we always run external initialization
      S_IDLE: begin
        state_next = S_START;
      end

      // One init cycle, then wait for Memory Controller
      S_START: begin
        state_next = S_WAIT;
      end

      // Normal init in progress
      S_WAIT: begin
        if (mem_init_done)
          state_next = S_FIRST_FETCH;
        else if (interrupt)
          state_next = S_SUCCESS;
        else
          state_next = S_WAIT;
      end

      //first instruction fetch
      S_FIRST_FETCH: begin
        state_next = S_SUCCESS;
      end

      // Terminal states: stay here until global reset
      S_SUCCESS: begin
        state_next = S_SUCCESS;
      end
      
      default: state_next = S_IDLE;
    endcase
  end

  // ==========================================================================
  // Output control logic
  //   Default = load/store mode (green in your diagram).
  // ==========================================================================
  always @* begin
    // ----- defaults: normal load/store mode -----
    mem_init       = 1'b0;
    SPI_rdata_type = 1'b1;   // 1 = EMBD_READ(load)
    PRAM_addr_type = 1'b1;   // 1 = LOAD/STORE address
    PRAM_in        = 1'b1;   // 1 = STORE data
    burst_dim      = 1'b1;   // 1 = LOAD/STORE
    ROM_addr_type  = 1'b1;   // 1 = EMAB(load/store address)
    first_fetch    = 1'b0;

    case (state)
      // Initialization states
      S_START, S_WAIT : begin
        mem_init       = 1'b1;   // we are in init phase
        SPI_rdata_type = 1'b0;   // SPI data used for init
        PRAM_addr_type = 1'b0;   // address from init counter
        PRAM_in        = 1'b0;   // initialization data into PRAM
        burst_dim      = 1'b0;   // "initialization" mode
        ROM_addr_type  = 1'b0;   // ROM address from init counter
        first_fetch    = 1'b0;
      end

      S_FIRST_FETCH : begin
        first_fetch   = 1'b1;
      end

      default: ;
    endcase
  end

endmodule

